

//2018-05-24: generated by Unity
//2018-05-24: pieces copied from https://gamedev.stackexchange.com/questions/92538/explaining-unity-sprite-default-shader
//2025-02-24: copied from LayerShader
				
Shader "SG7/LavaShader"
{
	Properties
	{
		[PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}

		_CenterPos ("Center Position", Vector) = (0, 0, 0)
		_BaseColor ("Base Color", Color) = (1,0,0,1)
		_BubbleColor1 ("Bubble Color 1", Color) = (1,1,0,1)
		_RendererColor ("Tint", Color) = (0,0,0,1)
	}
	SubShader
	{
		Tags
        { 
            "Queue"="Transparent" 
            "IgnoreProjector"="True" 
            "RenderType"="Transparent" 
            "PreviewType"="Plane"
            "CanUseSpriteAtlas"="True"
        }

		Cull Off
        Lighting Off
        ZWrite Off
        Fog { Mode Off }
        Blend One OneMinusSrcAlpha

		Pass
		{
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"

			struct appdata
			{
				float4 vertex : POSITION;
				float4 color : COLOR;
				float2 uv : TEXCOORD0;
			};

			struct v2f
			{
				float2 uv : TEXCOORD0;
				fixed4 color: COLOR;
				float4 vertex : SV_POSITION;
				float3 worldPos : TEXCOORD1;
			};

			fixed4 _RendererColor;
			float3 _CenterPos;
			fixed4 _BaseColor;
			fixed4 _BubbleColor1;


			v2f vert (appdata IN)
			{
				v2f OUT;
                OUT.vertex = UnityObjectToClipPos(IN.vertex);
                OUT.uv = IN.uv;
                OUT.color = IN.color * _RendererColor;
				//2025-01-25: copied from https://discussions.unity.com/t/getting-the-world-position-of-the-pixel-in-the-fragment-shader/177100/2
				OUT.worldPos =  mul (unity_ObjectToWorld, IN.vertex);

                return OUT;
			}

			sampler2D _MainTex;

			fixed4 frag (v2f i) : SV_Target
			{
				fixed4 curColor = tex2D(_MainTex, i.uv);
				fixed4 col = curColor * i.color;

				fixed4 color = _BaseColor;
					col = curColor * i.color * color;

				col *= _RendererColor;
				col.rgb *= col.a;
				return col;
			}


			
			ENDCG
		}
	}
}
