

//2018-05-24: generated by Unity
//2018-05-24: pieces copied from https://gamedev.stackexchange.com/questions/92538/explaining-unity-sprite-default-shader
//2025-02-24: copied from LayerShader
				
Shader "SG7/LavaShader"
{
	Properties
	{
		[PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}

		_CenterPos ("Center Position", Vector) = (0, 0, 0)
		_BaseColor ("Base Color", Color) = (1,0,0,1)
		_BubbleColor1 ("Bubble Color 1", Color) = (1,1,0,1)
		_RendererColor ("Tint", Color) = (0,0,0,1)
		_Size ("Size", float) = 1
		_Thickness("Thickness", float) = 0.1
		_Spacing("Spacing", float) = 1
		_LayerSpacing("Layer Spacing", float) = 1
		_Speed("Speed", float) = 1
		_SteadyVector ("Steady Vector (Up)", Vector) = (0, 1, 0)
	}
	SubShader
	{
		Tags
        { 
            "Queue"="Transparent" 
            "IgnoreProjector"="True" 
            "RenderType"="Transparent" 
            "PreviewType"="Plane"
            "CanUseSpriteAtlas"="True"
        }

		Cull Off
        Lighting Off
        ZWrite Off
        Fog { Mode Off }
        Blend One OneMinusSrcAlpha

		Pass
		{
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"

			struct appdata
			{
				float4 vertex : POSITION;
				float4 color : COLOR;
				float2 uv : TEXCOORD0;
			};

			struct v2f
			{
				float2 uv : TEXCOORD0;
				fixed4 color: COLOR;
				float4 vertex : SV_POSITION;
				float3 worldPos : TEXCOORD1;
			};

			fixed4 _RendererColor;
			float3 _CenterPos;
			fixed4 _BaseColor;
			fixed4 _BubbleColor1;
			float _Size;
			float _Thickness;
			float _Spacing;
			float _LayerSpacing;
			float3 _SteadyVector;


			v2f vert (appdata IN)
			{
				v2f OUT;
                OUT.vertex = UnityObjectToClipPos(IN.vertex);
                OUT.uv = IN.uv;
                OUT.color = IN.color * _RendererColor;
				//2025-01-25: copied from https://discussions.unity.com/t/getting-the-world-position-of-the-pixel-in-the-fragment-shader/177100/2
				OUT.worldPos =  mul (unity_ObjectToWorld, IN.vertex);

                return OUT;
			}
			//2025-02-24: made with help from https://stackoverflow.com/a/43494689/2336212
			float angleBetween(float3 v1, float3 v2){
				float theta = acos(dot(v1,v2) / length(v1) * length (v2));
				theta = theta * 360 / (2*3.14159);
				if (v1.x < 0){
					theta = 360-abs(theta);
				}
				return theta;
			}
			//2025-02-24: made with help from https://stackoverflow.com/a/18852077/2336212
			float3 angleToVector(float angle){
				//2025-02-24: copied from Google AI Overview
				float radians = angle * (3.14159 / 180.0); // Convert angle to radians
				//
				return float3( sin(radians),cos(radians), 0);
			}
			
			bool inBubble(float3 v){

				//find closest point
				float len = round(length(v)/_LayerSpacing)*_LayerSpacing;
				float time = (_Time) % _LayerSpacing;
				if (time > _LayerSpacing/2){
					time = time - _LayerSpacing;
					}
				len += time;
				float pointsThisLayer = len * 2 * 3.14159 / _Spacing;
				float angle = round(angleBetween(v, _SteadyVector)/_Spacing)*_Spacing;
				float3 closest = angleToVector(angle) * len;
				//if in range, return true
				float dist = distance(v, closest);
				return dist <= _Size && dist >= _Size - _Thickness;
			}

			sampler2D _MainTex;

			fixed4 frag (v2f i) : SV_Target
			{
				fixed4 curColor = tex2D(_MainTex, i.uv);
				fixed4 col = curColor * i.color;

				fixed4 color = _BaseColor;
				if (inBubble(i.worldPos)){
					color = _BubbleColor1;
				}
				// color.z = angleBetween(i.worldPos, _SteadyVector)/360;
				// color.z = angleBetween(angleToVector(angleBetween(i.worldPos, _SteadyVector)),_SteadyVector)/360;
					col =  i.color * color;

				col *= _RendererColor;
				col.rgb *= col.a;
				return col;
			}


			
			ENDCG
		}
	}
}
