

//2018-05-24: generated by Unity
//2018-05-24: pieces copied from https://gamedev.stackexchange.com/questions/92538/explaining-unity-sprite-default-shader
				
Shader "SG7/LayerShader"
{
	Properties
	{
		[PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}

		_CenterPos ("Center Position", Vector) = (0, 0, 0)
		_LayerHeight ("Layer Height", float) = 10.0
		_LayerColor1 ("Layer Color 1", Color) = (1,0,0,1)
		_LayerColor2 ("Layer Color 2", Color) = (0,1,0,1)
		_LayerColor3 ("Layer Color 3", Color) = (0,0,1,1)
		_Color ("Tint", Color) = (0,0,0,1)
	}
	SubShader
	{
		Tags
        { 
            "Queue"="Transparent" 
            "IgnoreProjector"="True" 
            "RenderType"="Transparent" 
            "PreviewType"="Plane"
            "CanUseSpriteAtlas"="True"
        }

		Cull Off
        Lighting Off
        ZWrite Off
        Fog { Mode Off }
        Blend One OneMinusSrcAlpha

		Pass
		{
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"

			struct appdata
			{
				float4 vertex : POSITION;
				float4 color : COLOR;
				float2 uv : TEXCOORD0;
			};

			struct v2f
			{
				float2 uv : TEXCOORD0;
				fixed4 color: COLOR;
				float4 vertex : SV_POSITION;
				float3 worldPos : TEXCOORD1;
			};

			fixed4 _Color;
			float3 _CenterPos;
			fixed4 _LayerColor1;
			fixed4 _LayerColor2;
			fixed4 _LayerColor3;
			float _LayerHeight;

			fixed4 getLayerColor(int layer){
				int index = layer % 3;
				if (index == 0){
					return _LayerColor1;
				}
				if (index == 1){
					return _LayerColor2;
				}
				if (index == 2){
					return _LayerColor3;
				}
				return _Color;
			}

			int getLayer(float3 v){
				return floor(distance(v, _CenterPos) / _LayerHeight);
			}

			v2f vert (appdata IN)
			{
				v2f OUT;
                OUT.vertex = UnityObjectToClipPos(IN.vertex);
                OUT.uv = IN.uv;
                OUT.color = IN.color * _Color;
				//2025-01-25: copied from https://discussions.unity.com/t/getting-the-world-position-of-the-pixel-in-the-fragment-shader/177100/2
				OUT.worldPos =  mul (unity_ObjectToWorld, IN.vertex);

                return OUT;
			}

			sampler2D _MainTex;

			fixed4 frag (v2f i) : SV_Target
			{
				fixed4 curColor = tex2D(_MainTex, i.uv);
				fixed4 col = curColor * i.color;
				int layer = getLayer(i.worldPos);

					col = curColor * i.color * getLayerColor(layer);

				col.rgb *= col.a;
				return col;
			}


			
			ENDCG
		}
	}
}
